# Generated by Django 4.1 on 2022-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("stock", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
            ],
        ),
    ]
